--liquibase formatted sql

--changeset razinkova:1
CREATE TABLE faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (255) NOT NULL,
    color VARCHAR(50) NOT NULL,
    balance NUMERIC(19, 2) DEFAULT 0 NOT NULL,
    curator_id BIGINT,
    starosta_id BIGINT,

    CONSTRAINT uq_faculty_name UNIQUE (name)
);

--changeset razinkova:2-seq
CREATE SEQUENCE IF NOT EXISTS student_ticket_seq START WITH 100000;

--changeset razinkova:2
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR (255) NOT NULL,
    last_name VARCHAR (255) NOT NULL,
    gender VARCHAR (20) NOT NULL,
    birth_date DATE NOT NULL,
    faculty_id BIGINT,
    user_status VARCHAR (70) NOT NULL,
    phone_number VARCHAR (255) NOT NULL,
    course SMALLINT,
    balance NUMERIC(19, 2) DEFAULT 0 NOT NULL,
    role VARCHAR(50) DEFAULT 'STUDENT' NOT NULL,
    student_ticket VARCHAR(50) DEFAULT to_char(nextval('student_ticket_seq'), 'FM000-000') NOT NULL,

    CONSTRAINT chk_users_gender CHECK (gender IN ('MALE', 'FEMALE')),
    CONSTRAINT chk_users_course CHECK (course BETWEEN 1 AND 6),
    CONSTRAINT uq_phone_number UNIQUE (phone_number),
    CONSTRAINT uq_student_ticket UNIQUE (student_ticket)
);

--changeset razinkova:2.1
 CREATE INDEX idx_student_last_name_lower ON users (LOWER(last_name));
 CREATE INDEX IF NOT EXISTS idx_users_phone_number ON users (phone_number);
 CREATE INDEX IF NOT EXISTS idx_users_student_ticket ON users (student_ticket);

--changeset razinkova:2.2
ALTER TABLE users
    ADD CONSTRAINT fk_users_faculty
    FOREIGN KEY (faculty_id) REFERENCES faculty (id);

ALTER TABLE faculty
    ADD CONSTRAINT fk_faculty_curator FOREIGN KEY (curator_id) REFERENCES users (id) ON DELETE SET NULL,
    ADD CONSTRAINT fk_faculty_starosta FOREIGN KEY (starosta_id) REFERENCES users (id) ON DELETE SET NULL;

--changeset razinkova:2.3
ALTER TABLE users
    ADD COLUMN email VARCHAR(255),
    ADD COLUMN password VARCHAR(255),
    ADD COLUMN activation_token VARCHAR(255);


--changeset razinkova:3
CREATE TABLE avatar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path VARCHAR (255) NOT NULL,
    file_path_preview VARCHAR (255) NOT NULL,
    file_size BIGINT NOT NULL,
    media_type VARCHAR (255) NOT NULL,
    data BYTEA,
    preview_avatar BYTEA,
    user_id BIGINT NOT NULL,

    CONSTRAINT uq_avatar_user_id UNIQUE (user_id),
    CONSTRAINT fk_avatar_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

--changeset razinkova:4
CREATE TABLE quest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR (255) NOT NULL,
    description VARCHAR (255) NOT NULL,
    date_start DATE,
    date_end DATE,
    archive BOOLEAN DEFAULT FALSE NOT NULL,
    course SMALLINT,

    CONSTRAINT chk_quest_dates_coexistence CHECK (
            (date_start IS NULL AND date_end IS NULL) OR
            (date_start IS NOT NULL AND date_end IS NOT NULL AND date_end >= date_start)),
    CONSTRAINT chk_quest_course CHECK (course BETWEEN 1 AND 6)
);

--changeset razinkova:5
CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR (255) NOT NULL,
    award NUMERIC(19, 2) NOT NULL,
    quest_id BIGINT,
    archive BOOLEAN DEFAULT FALSE NOT NULL,

    CONSTRAINT task_quest_id FOREIGN KEY (quest_id) REFERENCES quest (id)
);

--changeset razinkova:6
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (255) NOT NULL
);

--changeset razinkova:7.1
CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article VARCHAR (255) NOT NULL,
    archive BOOLEAN DEFAULT FALSE NOT NULL,
    product_name VARCHAR (255) NOT NULL,
    category_id BIGINT,
    main_pic VARCHAR(255),
    popular INT,
    price NUMERIC(19, 2) NOT NULL,
    teaser VARCHAR (500),
    temp_out BOOLEAN,
    quantity INT,

    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

--changeset razinkova:7.2
CREATE TABLE product_size (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    size_product VARCHAR(50) NOT NULL,
    quantity INT DEFAULT 0 NOT NULL,
    CONSTRAINT fk_product_size_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT uq_product_size_val UNIQUE (product_id, size_product)
);

--changeset razinkova:7.3
CREATE INDEX idx_product_size_product_id ON product_size (product_id);

--changeset razinkova:7.4
CREATE TABLE product_images (
    product_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    CONSTRAINT fk_product_images_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

--changeset razinkova:7.5
 CREATE INDEX idx_product_images_product_id ON product_images (product_id);

--changeset razinkova:7.6
CREATE TABLE product_faculties (
    product_id BIGINT NOT NULL,
    faculty_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, faculty_id),
    CONSTRAINT fk_prod_fac_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT fk_prod_fac_faculty FOREIGN KEY (faculty_id) REFERENCES faculty (id) ON DELETE CASCADE
);

--changeset razinkova:7.7
 CREATE INDEX idx_product_faculties_product_id ON product_faculties (product_id);

--changeset razinkova:8
CREATE TABLE balance_operation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(19, 4) NOT NULL,
    task_id BIGINT,
    user_id BIGINT NOT NULL,
    source_faculty_id BIGINT NOT NULL,
    creator_id BIGINT,
    operation_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'DRAFT' NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_balance_ops_task FOREIGN KEY (task_id) REFERENCES task (id),
    CONSTRAINT fk_balance_ops_student FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_balance_ops_faculty FOREIGN KEY (source_faculty_id) REFERENCES faculty (id),
    CONSTRAINT fk_balance_ops_creator FOREIGN KEY (creator_id) REFERENCES users (id),
    CONSTRAINT chk_balance_amount_positive CHECK (amount > 0)
);

--changeset razinkova:8.1
CREATE INDEX IF NOT EXISTS idx_balance_ops_user ON balance_operation (user_id);
CREATE INDEX IF NOT EXISTS idx_balance_ops_creator ON balance_operation (creator_id)